### ISSUE TITLE
转码服务在计费详情界面，没有列出切片封装服务的宽网价

### ISSUE THREAD

**Issue by lyonning** [huaweicloudDocs/vod#1]
转码服务在计费详情界面，没有列出切片封装服务的宽网价，页面地址：https://www.huaweicloud.com/pricing.html#/mpc

**Comment by chenxuefen-ada** [comment]
应该说是转封装的价格详情吧，已经提需求让产品上线

**Comment by chenxuefen-ada** [comment]
已经上线转封装价格
![image](https://user-images.githubusercontent.com/57934801/87111801-d5732000-c29c-11ea-9921-5809afe37914.png)
